// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXn-ROmMrfihh0v732gBmdyw02FeyE274',
    appId: '1:19881781652:web:0653eab232968c3c748781',
    messagingSenderId: '19881781652',
    projectId: 'tiktok-clone-jh',
    authDomain: 'tiktok-clone-jh.firebaseapp.com',
    storageBucket: 'tiktok-clone-jh.firebasestorage.app',
    measurementId: 'G-EN9JEW1ZD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5v3iMlY-AOUhrROZExA1l81c1Qqeea44',
    appId: '1:19881781652:android:3fd48b28157adc08748781',
    messagingSenderId: '19881781652',
    projectId: 'tiktok-clone-jh',
    storageBucket: 'tiktok-clone-jh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXAhJOmT-WVzHLESNPuglrFa8W2Cu8MHA',
    appId: '1:19881781652:ios:f287c69840602b5e748781',
    messagingSenderId: '19881781652',
    projectId: 'tiktok-clone-jh',
    storageBucket: 'tiktok-clone-jh.firebasestorage.app',
    iosBundleId: 'com.jhyoon.tiktokClone',
  );

}